// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAps67AZDEDOQAeOdlsPCLK3E-0lMZg7Y8',
    appId: '1:323993206789:android:66c3cad922082416729c6c',
    messagingSenderId: '323993206789',
    projectId: 'segari-e77e0',
    databaseURL: 'https://segari-e77e0.firebaseio.com',
    storageBucket: 'segari-e77e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD28EOHVI_OpivlZTTS6x4gkf_BAV6WPO8',
    appId: '1:323993206789:ios:9e43fffac6759f81729c6c',
    messagingSenderId: '323993206789',
    projectId: 'segari-e77e0',
    databaseURL: 'https://segari-e77e0.firebaseio.com',
    storageBucket: 'segari-e77e0.appspot.com',
    androidClientId: '323993206789-ce5jjjjo417or9f8i9u02uh4hvpirfeg.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectTes',
  );
}
